#!/usr/bin/env bash
# Regenerate requirements/*.lock from requirements/*.in.
#
# Walks the dependency closure of every package listed in *.in using
# importlib.metadata (so it only includes packages CloseCrab actually
# pulls in, NOT the entire system pip freeze which on cc-tw / gLinux
# would include hundreds of unrelated Ubuntu packages).
#
# Usage:
#   scripts/lock-deps.sh           # regenerate base.lock + voice.lock
#   scripts/lock-deps.sh --check   # verify lock matches current install (CI)
#
# Workflow when upgrading a dependency:
#   1. Edit requirements/base.in (or voice.in)
#   2. pip install --upgrade <pkg>     # locally bump
#   3. ./scripts/lock-deps.sh          # regenerate lock
#   4. Test: ./deploy.sh --bot         # verify install + import works
#   5. git diff requirements/          # review the closure change
#   6. git commit -m "deps: bump <pkg> to <ver> (...reason)"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$SCRIPT_DIR"

CHECK_MODE=false
if [[ "${1:-}" == "--check" ]]; then
    CHECK_MODE=true
fi

regenerate_lock() {
    local in_file="$1"   # e.g. requirements/base.in
    local lock_file="$2" # e.g. requirements/base.lock
    local label="$3"     # e.g. "base"
    local extra_in="${4:-}"  # optional second .in file to merge (e.g. base.in for voice closure)

    echo "[$label] Computing closure from $in_file ..."

    local top_list
    top_list=$(grep -vE '^\s*(#|$)' "$in_file" | awk '{print $1}')
    local extra_list=""
    if [[ -n "$extra_in" && -f "$extra_in" ]]; then
        extra_list=$(grep -vE '^\s*(#|$)' "$extra_in" | awk '{print $1}')
    fi

    local tmp
    tmp=$(mktemp)

    TOPS="$top_list" EXTRAS="$extra_list" python3 <<'PY' > "$tmp"
import importlib.metadata as md
import os
import sys

def norm(n):
    return n.lower().replace("_", "-").strip()

def walk(name, seen):
    n = norm(name)
    if n in seen:
        return
    seen.add(n)
    try:
        reqs = md.requires(n) or []
    except md.PackageNotFoundError:
        return
    for r in reqs:
        if ";" in r and "extra" in r:
            continue  # skip optional extras
        dep = (r.split(";")[0]
                .split()[0]
                .split("[")[0]
                .split(">=")[0].split("==")[0]
                .split("<")[0].split(">")[0].split("~")[0]
                .split("!")[0]
                .strip())
        if dep:
            walk(dep, seen)

tops = [n for n in os.environ.get("TOPS", "").split() if n]
extras = [n for n in os.environ.get("EXTRAS", "").split() if n]

seen = set()
for t in tops + extras:
    walk(t, seen)

# BASE_ONLY=1 means: extras represents the BASE deps we want to SUBTRACT
# from the closure so the output is only what tops adds beyond extras.
# Used to compute voice.lock = (voice + base closure) - base closure.
base_only = os.environ.get("BASE_ONLY") == "1"
if base_only and extras:
    base_seen = set()
    for t in extras:
        walk(t, base_seen)
    seen = seen - base_seen

for name in sorted(seen):
    try:
        ver = md.version(name)
        print(f"{name}=={ver}")
    except md.PackageNotFoundError:
        print(f"# SKIP {name} (not installed — Python stdlib backport?)", file=sys.stderr)
PY

    # Prepend header
    {
        sed -n "1,/^[^#]/p" "$lock_file" 2>/dev/null | grep '^#' || cat <<EOF
# CloseCrab $label dependencies — EXACT-PINNED.
# Generated by scripts/lock-deps.sh on $(date +%Y-%m-%d). DO NOT edit by hand.
EOF
        echo ""
        cat "$tmp"
    } > "${lock_file}.new"

    if $CHECK_MODE; then
        if diff -q "$lock_file" "${lock_file}.new" >/dev/null 2>&1; then
            echo "  ✓ $lock_file matches current install"
            rm -f "${lock_file}.new"
            return 0
        else
            echo "  ✗ $lock_file DRIFTED from current install:"
            diff "$lock_file" "${lock_file}.new" || true
            rm -f "${lock_file}.new"
            return 1
        fi
    fi

    mv "${lock_file}.new" "$lock_file"
    local count
    count=$(grep -cE '^[a-zA-Z0-9]' "$lock_file" || echo 0)
    echo "  Wrote $lock_file ($count packages)"
    rm -f "$tmp"
}

DRIFT=0

regenerate_lock requirements/base.in requirements/base.lock "base" || DRIFT=1

if [[ -f requirements/voice.in ]]; then
    BASE_ONLY=1 regenerate_lock requirements/voice.in requirements/voice.lock "voice" requirements/base.in || DRIFT=1
fi

if $CHECK_MODE && [[ $DRIFT -ne 0 ]]; then
    echo ""
    echo "Lock files are out of sync with installed packages."
    echo "Run scripts/lock-deps.sh to regenerate (no --check)."
    exit 1
fi
