#!/usr/bin/env bash
# init-wiki.sh — 初始化 Wiki repo
# 首次运行创建目录结构 + git init
# 已有 repo 时 git pull
set -euo pipefail

WIKI_REPO="${WIKI_REPO:-$HOME/my-wiki}"
WIKI_GCS="${CC_PAGES_WEB_ROOT:-/gcs/cc-pages}/wiki"
GITHUB_REPO="${WIKI_GITHUB_REPO:-git@github.com:yangwhale/my-wiki.git}"

echo "=== CC Wiki Init ==="
echo "Repo: $WIKI_REPO"
echo "GCS:  $WIKI_GCS"

# Case 1: repo already exists → pull
if [ -d "$WIKI_REPO/.git" ]; then
    echo "Repo exists, pulling latest..."
    cd "$WIKI_REPO" && git pull --ff-only 2>/dev/null || echo "Pull skipped (no remote or no changes)"
    echo "Done. Repo is up to date."
    exit 0
fi

# Case 2: repo doesn't exist but remote does → clone
if git ls-remote "$GITHUB_REPO" &>/dev/null 2>&1; then
    echo "Cloning from $GITHUB_REPO..."
    git clone "$GITHUB_REPO" "$WIKI_REPO"
    echo "Done. Cloned successfully."
    exit 0
fi

# Case 3: nothing exists → create from scratch
echo "Creating new Wiki repo..."

mkdir -p "$WIKI_REPO"/{wiki/{sources,entities,concepts,analyses},raw/{articles,papers,transcripts,notes},wiki-data}

cd "$WIKI_REPO"
git init

# Copy style.css from skill references
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
if [ -f "$SKILL_DIR/references/style.css" ]; then
    cp "$SKILL_DIR/references/style.css" wiki/style.css
    echo "Copied style.css"
fi

# Create empty graph.json
cat > wiki-data/graph.json << 'GRAPH'
{
  "meta": {
    "updated": "",
    "node_count": 0,
    "link_count": 0
  },
  "nodes": [],
  "links": []
}
GRAPH

# Create empty log.json
cat > wiki-data/log.json << 'LOGJSON'
{
  "entries": []
}
LOGJSON

# Create .gitignore
cat > .gitignore << 'GI'
.DS_Store
*.swp
*~
GI

# Create empty log.html placeholder (will be properly generated by rebuild scripts)
cat > wiki/log.html << 'LOG'
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Log — CC Wiki</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<nav class="wiki-nav">
  <a href="index.html">Index</a>
  <a href="graph.html">Graph</a>
  <a href="log.html" class="active">Log</a>
</nav>
<article class="wiki-content">
  <h1>Operation Log</h1>
  <div id="log-entries">
    <p class="wiki-empty">No operations yet. Use <code>/wiki ingest</code> to get started.</p>
  </div>
</article>
<footer class="wiki-footer">CC Wiki · Maintained by CloseCrab Bot</footer>
</body>
</html>
LOG

# Initial commit
git add -A
git commit -m "init: CC Wiki repo structure

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>"

echo ""
echo "Wiki repo created at $WIKI_REPO"
echo "Next steps:"
echo "  1. Create GitHub private repo: gh repo create yangwhale/my-wiki --private"
echo "  2. Push: cd $WIKI_REPO && git remote add origin $GITHUB_REPO && git push -u origin main"
echo "  3. Run: python3 ~/.claude/skills/wiki/scripts/sync-to-gcs.py"
